// examples/vue/src/App.vue
<template>
  <div>
    height:
    <select v-model="height">
      <option value="600px">600px</option>
      <option value="800px">800px</option>
    </select>
    text:
    <input v-model="titleText" />
    <vite-react-webcomponents userName="Joe_Sky" :titleText="titleText" :height="height">
      Try modifying the textbox at the top
    </vite-react-webcomponents>
  </div>
</template>

<script>
import '@joe-sky/vite-react-webcomponents/es/vue';

export default {
  name: 'App',
  data: () => ({
    height: '600px',
    titleText: 'ViteReactWebcomponents example with Vue v3!'
  })
};
</script>

<style lang="less" scoped>
select {
  margin-bottom: 10px;
  margin-right: 15px;
}

input {
  width: 300px;
}
</style>

// examples/react/src/App.tsx
import React, { useState } from 'react';
import './App.css';
import 'antd/dist/antd.css';
import { Card, Icon, Input } from 'antd';
import ViteReactWebcomponents from '@joe-sky/vite-react-webcomponents';

function App() {
  const [titleText, setTitleText] = useState('ViteReactWebcomponents example with React v16!');

  return (
    <div className="App">
      <Card
        title={
          <>
            <Icon type="user" style={{ marginRight: 10 }} />
            React v16 + Ant Design v3 Example
            <Input style={{ marginLeft: 30 }} value={titleText} onChange={e => setTitleText(e.target.value)} />
          </>
        }>
        <ViteReactWebcomponents userName="Joe_Sky" titleText={<b>{titleText}</b>} height="100%">
          <i>Try modifying the textbox at the top</i>
        </ViteReactWebcomponents>
      </Card>
    </div>
  );
}

export default App;
